myportfolio/urls.py
from django.urls import path

from . import views

app_name= 'myportfolio'

urlpatterns =[

    path("",views.index,name="index"),
    # path("projects",views.projects,name="projects"),
    path("experiences",views.experiences,name="experiences"),
    # path("skills",views.skills,name="skills"),
    # path("contact",views.contact,name="contact"),
    #  path('contact/', views.contact, name='contact'),
    # path('contact', views.contact_us, name='contact_us'),

    # path('success/', views.success, name='success'),

    path('blogs/', views.Blogs, name='Blogs'),
    path('blogs/<id>/', views.detail, name='detail')

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("myportfolio.urls")),
    
]


urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myportfolio/models.py
from django.db import models
import os
# Create your models here.
from django.conf import settings
from datetime import date,datetime
import re

class Project(models.Model):

    title = models.CharField(max_length=500)
    description = models.CharField(max_length=2000)
    github_link = models.CharField(max_length=2000)
    tech_stack = models.CharField(max_length=500)
    image = models.FilePathField(path=os.path.join(settings.BASE_DIR, "myportfolio/static/img"), default="")

    @property
    def image_path(self):
        return re.sub('.*img/','',self.image)

    def __str__(self):
        return self.title


class Blog(models.Model):
    title = models.CharField(max_length=500)
    description = models.CharField(max_length=2000)
    image =models.CharField(max_length=1000,default="",blank=True)
    published_on = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.title


class Experience(models.Model):
    designation = models.CharField(max_length=500)
    start_date = models.DateField()
    end_date = models.DateField(blank=True)
    is_present = models.BooleanField(null=True,blank=True)
    responsibilities_1 = models.CharField(max_length=2000,default=None,blank=True)
    responsibilities_2 = models.CharField(max_length=2000,default=None,blank=True)
    responsibilities_3 = models.CharField(max_length=2000,default=None,blank=True)
    responsibilities_4 = models.CharField(max_length=2000,default=None,blank=True)
    company = models.CharField(max_length=200,default=None,blank=True)
    location = models.CharField(max_length=200,default=None,blank=True)


    def __str__(self):
        return self.designation


class Skill(models.Model):

    name = models.CharField(max_length=50)
    image =models.CharField(max_length=1000)
    # image = models.FilePathField(path=os.path.join(settings.BASE_DIR, "myportfolio/static/img"), default="")


    def __str__(self):
        return self.name


class SendMail(models.Model):
    subject = models.CharField(max_length=100)
    useremail = models.EmailField(max_length=100)
    message = models.TextField()
    def __str__(self):
        return self.subject
  

class Profile(models.Model):
    name = models.CharField(max_length=100)
    designation = models.CharField(max_length=500)
    summary = models.CharField(max_length=5000)
    image = models.FilePathField(path=os.path.join(settings.BASE_DIR, "myportfolio/static/img"), default="")
    phone_number = models.CharField(max_length=100)
    email = models.EmailField()
    fb_link = models.URLField()
    github_link = models.URLField()
    insta_link = models.URLField()
    linkedin_link = models.URLField()


    def __str__(self):
        return self.name

myportfolio/forms.py
from django.core import validators
from django import forms
from .models import SendMail

class UserSendMail(forms.ModelForm):
    class Meta:
        model = SendMail
        fields = ['subject', 'useremail', 'message']
        widgets = {
            'subject': forms.TextInput(attrs={'placeholder': 'Write your Subject','class':'input-subject'}),
            'useremail': forms.EmailInput(attrs={'placeholder': 'Write your Mailing Address','class':'input-to'}),
            'message': forms.Textarea(attrs={'placeholder': 'Write something..','class':'input-message'})
        }

myportfolio/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, Context
from .models import Project, Blog, Skill, SendMail,Experience,Profile
# Create your views here.
from .forms import UserSendMail
from django.contrib import messages
from django.core.mail import send_mail,BadHeaderError


def index(request):
    #template = loader.get_template("myportfolio/index.html")
    projects = Project.objects.all()
    skills = Skill.objects.all()
    experiences = Experience.objects.all().order_by('-start_date')[:5]
    profile = Profile.objects.all().first()
    form = UserSendMail()
    context = {'projects': projects, 'skills': skills, 'form': form,'experiences':experiences,'profile':profile}
    #return HttpResponse(template.render(context, request))
    if request.method=='GET':
        return render (request,'myportfolio/index.html',context)

    if request.method == 'POST':
        # mail_form = UserSendMail(request.POST)
        if mail_form.is_valid():
            subject = request.POST.get('subject')
            message = request.POST.get('message')
            _from = 'rushikeshtole19@gmail.com'
            useremail = request.POST.get('useremail')
            mail_data = SendMail(subject=subject, message=message, useremail=useremail)
            mail_data.save()
            # msgm=msg.replace("<|message|>", message)
            # msgu=msgm.replace("<|NAME|>", useremail)
            # msgs=msgu.replace("|<topic|>", subject)

            send_mail(
                subject,
                message,
                _from,
                [useremail],
                fail_silently=False,
            )
            mail_form = UserSendMail(request.POST)
            return render (request,'myportfolio/index.html',context)
        
        else:
            mail_form = UserSendMail(request.POST)

            return render (request,'myportfolio/index.html', context)
    else:
        mail_form = UserSendMail(request.POST)
        return render (request,'myportfolio/index.html', context)

def experiences(request):
    return HttpResponse("you are in experience page")

def Blogs(request):
    blogs = Blog.objects.order_by('-published_on')
    return render (request, 'myportfolio/blog.html', {'blogs':blogs})

def detail(request,id):
    blog = get_object_or_404(Blog, id=id)
    return render (request, 'myportfolio/blog_details.html', {'blog':blog})    

msg = '''[<|message|>]'''

def contact_us(request):
    if request.method=='GET':
        #template = loader.get_template("myportfolio/index.html")
        projects = Project.objects.all()
        skills = Skill.objects.all()
        experiences = Experience.objects.all().order_by('-start_date')[:5]
        profile = Profile.objects.all().first()
        form = UserSendMail()
        context = {'projects': projects, 'skills': skills, 'form': form,'experiences':experiences,'profile':profile}
        return render (request,'myportfolio/index.html',context)
        
    if request.method == 'POST':
        mail_form = UserSendMail(request.POST)
        if mail_form.is_valid():
            subject = request.POST.get('subject')
            message = request.POST.get('message')
            _from = 'rushikeshtole19@gmail.com'
            useremail = request.POST.get('useremail')
            mail_data = SendMail(subject=subject, message=message, useremail=useremail)
            mail_data.save()
            # msgm=msg.replace("<|message|>", message)
            # msgu=msgm.replace("<|NAME|>", useremail)
            # msgs=msgu.replace("|<topic|>", subject)

            send_mail(
                subject,
                message,
                _from,
                [useremail],
                fail_silently=False,
            )
            mail_form = UserSendMail(request.POST)
            return render (request,'myportfolio/contact.html', {'messages':'Mail Send Successfully'})
        
        else:
            mail_form = UserSendMail(request.POST)

            return render (request,'myportfolio/contact.html', {'messages':'Mail Not Send','form':mail_form})
    else:
        mail_form = UserSendMail(request.POST)
        return render (request,'myportfolio/contact.html', {'messages':'Write','form':mail_form})

myportfolio/templates/myportfolio/base.html
<!DOCTYPE html>
<html>
<head>
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  position: sticky;
  top: 0;
  background-color: #333;
  overflow: hidden;
  background-color: #212529;
  font-family: "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
  font-weight: 700;
  

}
/*      hhhhkk  */
.topnav a {
  float: right;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: red;
}

.topnav a.active {
  background-color: #212529;
  color: white;
}

.blackiconcolor {color:white;}
.up{
  margin-left: 1485px;
  font-size: 47px;
  font-family: bold;
  color: white;
}
</style>
  <title>Rushi's profile</title>
  <link rel="icon" type="image/png" href="{% static 'img/myicon.png' %}"/>
</head>
<body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<div class="topnav">
  <a class="contacts" href="}">Contact</a>
  <a class="Resume" href="https://drive.google.com/file/d/1z8NPk1WhC6s03wbncdvnEcQi7PQTPzQk/view?usp=drivesdk">Resume</a>
  <a href="{% url 'myportfolio:Blogs'  %}">Myblogs</a>
  <a class="experience" href="{% url 'myportfolio:experiences'  %}">Experience</a>
  <a class="project"  href="/">Projects</a>
  <a class="Skills" href="#Skills">Skillset</a>
  <a class="active1" href="{% url 'myportfolio:index' %}">Home</a>
</div>

{% block page_content %}
{% endblock %}
{% block content %}
{% endblock content %}
<a href="{% url 'myportfolio:index' %} " class="up">⬆️</a>
</body>
</html>

myportfolio/templates/myportfolio/blog.html
{% extends "myportfolio/base.html" %} {% load static %} {% block content %}
<style>
.blogs{
        
    display:grid;
    grid-template-columns: repeat(4,1fr);
    gap:2px;
}
{% comment %} .oneblog{
    background-color:#111010;


} {% endcomment %}
body{
 background-image: url('https://64.media.tumblr.com/f74d7cc35e3c4ed6fc11f560fe38b2a7/tumblr_inline_ny82m7qGH41ro20i7_500.gifv'); 

}
h1{
    color:#9e9a9a;
    text-decoration: underline;
}
h2{
    color: #a0a09a;
}
h4{
    color:#a8a1a1;
}
button{
    background-color: #3d3d3d;
    color: #b0abab;
    border: 1px solid #bc0808;
}
</style>
<body class"body">
<h1 id="blogtitle" class="font-weight-bold text-center">MyBlogs</h1>
<div class="blogs">
{% for blog in blogs %}
<div class="oneblog">
  <div class="col-md-10">
    
      <center><h2>{{ blog.title }}</h2>
  
    <h5 class="text-muted">{{ blog.published_on.date|date:'d M Y'|upper }}</h5>
</center>
    <h4>{{ blog.description|striptags|truncatechars:30 }}</h4>
    <a href="{% url 'myportfolio:detail' blog.id %}">  
        <button>View</button>
    </a>
  </div>
</div>
{% endfor %} 
</div>
{% endblock content %}
</body>

myportfolio/templates/myportfolio/blog_details.html
{% extends "myportfolio/base.html" %}

{% load static %}

{% block content %}

<style>
    body{
 background-image: url('https://64.media.tumblr.com/f74d7cc35e3c4ed6fc11f560fe38b2a7/tumblr_inline_ny82m7qGH41ro20i7_500.gifv'); 
    }
 h1{
    color: grey;
    text-decoration: underline;
 }
 .description{
     color:grey;
     font-size:19px
 }
 .img{
    width: 250px;

 }
 a{
     font-size:20px;
     color:whitesmoke;
 }
    
</style>
<a href="{% url 'myportfolio:Blogs' %}">⬅️ back</a>
<body class="body">
<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.published_on.date|date:'F jS Y' }}</h5>
<div class="img1">
    <center>
    <img id="blog-image" src={{blog.image}} alt={{ blog.title }} class="img">
    <center>
</div>


    <center class="description">
{{ blog.description|safe }}
    </center>

{% endblock content %}
</body>

myportfolio/templates/myportfolio/contact.html
{% extends "myportfolio/base.html" %}
{% include  %}

{% block page_content %}

<div>

    <form method="post" actions="">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions" >
      <button type="submit">Send</button>
    </div>
</form>

    <h3 align="center" > Thanks for connecting with me!!!!</h3>
    <a href="/myportfolio">Go to home page</a>

</div>

{% endblock %}

myportfolio/templates/myportfolio/index.html
{% extends "myportfolio/base.html" %}

{% load crispy_forms_tags %}
{% block page_content %}

{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<style>



.profile-info{
 margin-top:50px;
 float: right;
 margin-left:32rem;
 font-family: "Montserrat", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";

 color: #000000;
 color:#9e9a9a;
 font-size: 17px;

}



body
{
 background-image: url('https://64.media.tumblr.com/f74d7cc35e3c4ed6fc11f560fe38b2a7/tumblr_inline_ny82m7qGH41ro20i7_500.gifv'); 
 min-height: auto;
}
.contact{
  background-image: url('https://64.media.tumblr.com/f74d7cc35e3c4ed6fc11f560fe38b2a7/tumblr_inline_ny82m7qGH41ro20i7_500.gifv'); 

}
h4 {
  margin-bottom: 30px;
}

#project-header,#skill-header {
text-align: center
}
.containermy-4{

  display: flex;
  justify-content: left;
  margin-left:150px;
  margin-top:50px;
}
.fa{
  color: #000000;
}

.contact {
  /* background-color: #171414; */
    width: 322px;
    border: 5px solid black;
    padding: 50px;
    margin: 20px;
    width: 32%;
    margin: 0 auto;
    /* margin-top: 112px; */
}

.email-me{
background-color: skyblue;
width:120px;
}

.avatar {
    background-color: #66ffff;
    border: 5px solid  #7d8484;
    width: 310px;
    margin-left: -62px;
}


.skills1 {
  display: flex;
  flex-wrap: wrap;
  padding: 0 4px;

}

.skill {
  flex: 11.11%;
  padding: 0 50px;
  max-width: 11.11%;
}

.skill img {
  margin-top: 20px;
  vertical-align: middle;
  width: 100%;

}

.div-border{
 padding: 10px;
 border: 0.1px solid  #bfbfbf;
}


.resume{
    padding-left: 80px;
}

.resume-title {

  margin-top: 30px;
  margin-bottom: 20px;
  color: #9e9a9a;

}

.resume .resume-item {
  padding: 0 0 20px 20px;
  margin-top: -2px;
  border-left: 2px solid #0563bb;
  position: relative;
}

.resume .resume-item h4 {
  line-height: 18px;
  font-size: 18px;
  font-weight: 600;
  text-transform: uppercase;
  font-family: "Poppins", sans-serif;
  color: #0563bb;
  margin-bottom: 10px;
}

.resume .resume-item h5 {
  font-size: 16px;
  background: #f7f8f9;
  padding: 5px 15px;
  display: inline-block;
  font-weight: 600;
  margin-bottom: 10px;
}

.resume .resume-item ul {
  padding-left: 20px;
}

.resume .resume-item ul li {
  padding-bottom: 10px;
}

.resume .resume-item:last-child {
  padding-bottom: 0;
}

.resume .resume-item::before {
  content: "";
  position: absolute;
  width: 16px;
  height: 16px;
  border-radius: 50px;
  left: -9px;
  top: 0;
  background: #fff;
  border: 2px solid #0563bb;
}

.name{
  Color:#9e9a9a;;
}
.facebook,.instagram,.github,.linkedin,.gmail,.number{
  background-color: #9e9a9a;
  font-size: 30px;
  margin: 5px;
}

.head{
  color: #9e9a9a;
  text-decoration: underline;
  
}
.connect{
  color: #9e9a9a;
  text-decoration: underline;

}
.resume{
  color: #9e9a9a ;
}
h5{
  color: #312e2e ;
}
.projects{
  
        
        display:grid;
        grid-template-columns: repeat(4,1fr);
        gap:22px;
        width: 100px;
  
}
.card{
  margin-left: 33px;
}
.btn{
  color: #010000;
    background-color: #858885;
    border-color: #ec0539;
}

</style>
<div class ="profile">
<div class="profile-info">

    <!-- <h3 class ="name">Hey <img src="https://raw.githubusercontent.com/ABSphreak/ABSphreak/master/gifs/Hi.gif" width="30px" style="max-width: 100%;"> I'm {{profile.name}}</h3> -->
    <img class="deco" src="https://camo.githubusercontent.com/a687d35ab84bd95f6784f1bad03abdb01081a0ab2406dd78b5206da5f0469721/68747470733a2f2f726561646d652d747970696e672d7376672e6865726f6b756170702e636f6d3f666f6e743d417263686974656374732b446175676874657226636f6c6f723d7265642673697a653d3330266c696e65733d48656c6c6f212b497427732b52757368696b6573682b546f6c65213b46756c6c2b537461636b2b446576656c6f7065722e2e2e3b" alt="Typing SVG" data-canonical-src="https://readme-typing-svg.herokuapp.com?font=Architects+Daughter&amp;color=red&amp;size=30&amp;lines=Hello!+It's+Rushikesh+Tole!;Full+Stack+Developer...;" style="max-width: 100%;">
    <h6 class="card-subtitle mb-2 text-muted">{{ profile.designation}}</h6>
    <p >{{profile.summary}}</p>

    <div class="icon-bar">
      <a href={{profile.fb_link}} class="facebook"><i class="fa fa-facebook"></i></a>
        <a href={{profile.insta_link}} class="instagram"><i class="fa fa-instagram"></i></a>
        <a href={{profile.github_link}} class="github"><i class="fa fa-github"></i></a>
      <a href={{profile.linkedin_link}} class="linkedin"><i class="fa fa-linkedin"></i></a>
        <a href=mailto:{{profile.email}} class="gmail"><i class="fa fa-envelope"></i></a>
      <a href="tel:+91-9579419991" cm_dontconvertlink class="number"><i class="fa fa-phone" aria-hidden="true"></i></a>

    </div>
    </section>
</div>

<div class="containermy-4">
    <div class="row text-center">
      <div class="col-md-6 mb-4">
        <img class="rounded-circle avatar"  src="{% static 'img/profile.jpg' %}" data-holder-rendered="true" width="100%">
      </div>
    </div>
</div>

</div>

<section class="Skills" id="Skills">
<h4 id="skill-header" class="head" >My Skills</h4>
<div class="div-border">

    <div class="skills1">
    {% for skill in skills %}
    <div class="skill">
        <img id="skill-image" title={{skill.name}}  src={{skill.image}} alt={{skill.name}} class="skill-data">
    </div>
    {% endfor %}

</div>
</div>
</section>
<hr>


<section class="project" id="project">

<h4 id="project-header"  class="head" >My Projects</h4>

<div class="projects">

  {% for project in projects %}
  <div class="row">
  <div class="col-sm-6">
    <div class="card" style="width: 20rem;">
        {% static "" as baseUrl %}
      <img class="card-img-top" src="{{ baseUrl }}img/{{project.image_path}}">
      <div class="card-body">
        <h5 class="card-title">{{project.title}}</h5>
        <p class="card-text">{{project.description}}</p>
        <a href={{project.github_link}} class="btn btn-primary" target="_blank">View code</a>
      </div>
    </div>
  </div>
</div>
  {% endfor %}
</div >

</section>
<hr>


<section class="experience" id="experience">

<h3 align="center" class="resume-title"  class="head" >Professional Experience</h3>

<section id="resume" class="resume">
 <div class="col-lg-6">
            {% for exp in experiences %}
            <div class="resume-item">
              <h4>{{exp.designation}}</h4>
                  {% if exp.is_present %}
                    <h5>{{exp.start_date}} - present</h5>
                {% else %}
                    <h5>{{exp.start_date}} - {{exp.end_date}}</h5>
                {% endif %}

              <p><em>{{exp.company}}, {{exp.location}} </em></p>
              <ul>
                  {% if exp.responsibilities_1 is not None %}
                    <li>{{exp.responsibilities_1}}</li>
                  {% endif %}
                  {% if exp.responsibilities_2 %}
                    <li>{{exp.responsibilities_2}}</li>
                  {% endif %}
                  {% if exp.responsibilities_3 %}
                    <li>{{exp.responsibilities_3}}</li>
                  {% endif %}
                  {% if exp.responsibilities_4 %}
                    <li>{{exp.responsibilities_4}}</li>
                  {% endif %}



              </ul>
            </div>
            {% endfor %}

          </div>

</section>
</section>
<hr>

<section class="contacts" id="contacts">

<div class="contact">
    <h3 align="center"  class="connect" >Connect with me </h3>
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn">Send Now</button>
  </form>

<!--    <p> I love to connect with people and solve the problems and help the world</p>-->
<!--    <div class="email-me">-->
<!--        <a class="bt btn primary" href = "mailto:jebaseelanravi96@gmail.com">Send Email</a>-->
</div>





 {% endblock %}

</section>